### ISSUE TITLE
Change of language model?

### ISSUE THREAD

**Issue by ryancoolround** [lin2025/gpt3.5#1]
Is there any way to change the model from e.g. gpt-3.5-turbo to ada because it is cheaper?

**Comment by lin2025** [comment]
Hi, I am new to GitHub. I saw your email message last night and made changes today. I created new repositories at [https://github.com/lin2025/gpt-3-web/](https://github.com/lin2025/gpt-3-web/) . If you are referring to the '**text-ada-001**' and '**ada**' models under the GPT-3 model, they can now be used. To modify them, search for "axios.post" in the code and update the 'model' parameter in two places.

**Comment by ryancoolround** [comment]
Thank you so much!
